name: Clean PR Deployment

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.PR_REPO }}
          ssh-key: ${{ secrets.PR_REPO_SSH_KEY }}
          ref: gh-pages
          path: gh-pages
      - name: Make commit to deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git rm ./pr${{ github.event.number }} || true
          git commit -m "pr${{ github.event.number }} build" || true
          git push origin gh-pages || true
        working-directory: gh-pages
