name: Deploy PR

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Yarn install
        run: |
          yarn install --immutable --immutable-cache
      - name: Setup .env
        run: |
          printf '%s' "$ENVFILE" > apps/frontend/.env.local
        env:
          ENVFILE: ${{ secrets.ENVFILE }}
      - name: Build genshin-optimizer
        run: |
          NX_URL_GITHUB_GO_CURRENT_VERSION="https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)" \
          NX_DAEMON="false" \
          yarn run nx run frontend:build:production --base-href=""
      - name: Checkout external gh-pages
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.PR_REPO }}
          ssh-key: ${{ secrets.PR_REPO_SSH_KEY }}
          ref: gh-pages
          path: gh-pages
      - name: Move to external gh-pages
        run: |
          mkdir --parents "gh-pages/pr${{ github.event.number }}"
          rm -rfv "gh-pages/pr/${{ github.event.number }}" || true
          mv "dist/apps/frontend" "gh-pages/pr/${{ github.event.number }}"
      - name: Make commit to deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./pr/${{ github.event.number }}
          git commit -m "build pr/${{ github.event.number }} $(git rev-parse HEAD)"
          git push origin gh-pages
        working-directory: gh-pages
      - name: Echo deployment URL
        run: |
          IFS=- read -r account repo <<< ${{ vars.PR_REPO }}
          echo 'Deployed to https://$account.github.io/$repo/pr/${{ github.event.number }} (Takes 3-5 minutes after this completes to be available)'
